name       : vscode
version    : 0.10.10
release    : 4
source     :
    - http://stroblindustries.com/solus-tarballs/vscode-0.10.10.tar.gz : 9c5529e66c2864212d336e5ed888b270dd37435312ebc9790f210461cc8df3d7
license    : MIT
summary    : VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
extract    : no
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - nodejs
    - tree
build    : |
    cd $srcdir
    tar -xf $sources/$version.tar.gz
    cd vscode-$version/
    npm install -g mocha gulp
    ./scripts/npm.sh install
    gulp vscode-linux-x64
install  : |
    cd $srcdir
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/opt/vscode
    cp -R $srcdir/VSCode-linux-x64/* $installdir/opt/vscode/
    ln -s /opt/vscode/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $srcdir/vscode-$version/resources/linux/code.png $installdir/usr/share/pixmaps/code-oss.png
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
