name       : vscode
version    : 1.14.1
release    : 35
source     :
    - https://github.com/Microsoft/vscode/archive/1.14.1.tar.gz : 9d65236ffa35a167d8891e00676190fd035e1edf2c5bbdd4cef6b181545ca45e
license    : MIT
component  : programming.ide
summary    : Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
rundeps    :
    - libxscrnsaver
    - nodejs
replaces   :
    - vscode-ms
setup      : |
    npm install gulp
    ./scripts/npm.sh install --arch=x64 --unsafe-perm
build      : |
    node ./node_modules/gulp/bin/gulp.js vscode-linux-x64
install    : |
    export vsdir=/usr/share/vscode
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/$vsdir
    cp -R $workdir/VSCode-linux-x64/* $installdir/$vsdir/
    ln -s $vsdir/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $pkgfiles/product.json $installdir/$vsdir/resources/app/product.json
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
    rm -rf $installdir/$vsdir/resources/app/resources/linux/*.png
