name       : vscode
version    : 1.44.0
release    : 104
source     :
    - git|https://github.com/Microsoft/vscode.git : 1.44.0
license    :
    - GPL-3.0-or-later # Icon (from Papirus)
    - MIT # VS Code
component  : programming.ide
summary    : Visual Studio Code (open source version) is a new type of tool that combines
    the simplicity of a code editor with what developers need for their core edit-build-debug
    cycle.
description: |
    Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - git
    - yarn
rundeps    :
    - git
    - libxscrnsaver
    - nodejs
replaces   :
    - vscode-ms
setup      : |
    %patch -p1 < $pkgfiles/0001-Attempt-to-symlink-.config-Code-to-.config-Code-OSS-.patch
    yarn
build      : |
    yarn run gulp vscode-linux-x64
install    : |
    export vsdir=/usr/share/vscode
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/$vsdir
    cp -R $workdir/../VSCode-linux-x64/* $installdir/$vsdir/
    ln -s $vsdir/bin/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $pkgfiles/product.json $installdir/$vsdir/resources/app/product.json
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
    install -Dm644 $pkgfiles/visual-studio-code.svg $installdir/usr/share/icons/hicolor/scalable/apps/visual-studio-code.svg
    install -Dm755 $pkgfiles/code-oss $installdir/$vsdir/bin/code-oss
    rm -rf $installdir/$vsdir/resources/app/resources/linux/*.png
    install -Dm00644 $installdir/$vsdir/resources/completions/bash/code-oss $installdir/usr/share/bash-completion/completions/code-oss
    install -Dm00644 $installdir/$vsdir/resources/completions/zsh/_code-oss $installdir/usr/share/zsh/site-functions/_code-oss
