name       : vscode
version    : 1.21.0
release    : 52
source     :
    - https://github.com/Microsoft/vscode/archive/1.21.0.tar.gz : d4773e3c136a311098c245a42f671eb1c90382f8e199f73dca500b0c15e41ba4
license    : MIT
component  : programming.ide
summary    : Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - git
    - yarn
rundeps    :
    - git
    - libxscrnsaver
    - nodejs
replaces   :
    - vscode-ms
setup      : |
    %patch -p1 < $pkgfiles/0001-Attempt-to-symlink-.config-Code-to-.config-Code-OSS-.patch
    yarn add gulp
    yarn
build      : |
    yarn run gulp vscode-linux-x64
install    : |
    export vsdir=/usr/share/vscode
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/$vsdir
    cp -R $workdir/VSCode-linux-x64/* $installdir/$vsdir/
    ln -s $vsdir/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $pkgfiles/product.json $installdir/$vsdir/resources/app/product.json
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
    install -Dm644 $installdir/$vsdir/resources/app/resources/linux/code.png $installdir/usr/share/pixmaps/visual-studio-code.png
    rm -rf $installdir/$vsdir/resources/app/resources/linux/*.png
