name       : vscode
version    : 1.9.1
release    : 24
source     :
    - https://github.com/Microsoft/vscode/archive/1.9.1.tar.gz : c059c7be89d3ac869622f59125fbd2e4d70056f5e348ae91c538fd90648358ac
license    : MIT
component  : programming.ide
summary    : Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
rundeps    :
    - libxscrnsaver
    - nodejs
replaces   :
    - vscode-ms
build      : |
    npm install gulp mocha
    ./scripts/npm.sh install --unsafe-perm
    node ./node_modules/gulp/bin/gulp.js vscode-linux-x64
install    : |
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/opt/vscode
    cp -R $workdir/VSCode-linux-x64/* $installdir/opt/vscode/
    ln -s /opt/vscode/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $pkgfiles/product.json $installdir/opt/vscode/resources/app/product.json
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
    rm -rf $installdir/opt/vscode/resources/app/resources/linux/*.png
