name       : vscode
version    : 1.3.0
release    : 6
source     :
    - https://github.com/Microsoft/vscode/archive/1.3.0.tar.gz : 36beedd8e19c9ca148a6d97b01291b0d31c2f8bfdd49142042d96a0e37d59233
license    : MIT
component  : editor
summary    : Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    Visual Studio Code (open source version) is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - git
    - nodejs
build      : |
    npm install -g mocha gulp
    ./scripts/npm.sh install
    gulp vscode-linux-x64
install    : |
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/opt/vscode
    cp -R $workdir/VSCode-linux-x64/* $installdir/opt/vscode/
    ln -s /opt/vscode/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $workdir/vscode-$version/resources/linux/code.png $installdir/usr/share/pixmaps/code-oss.png
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
