name       : vscode
version    : 0.10.10
release    : 1
source     :
    - https://github.com/Microsoft/vscode/archive/0.10.10.tar.gz : 45b59a96dacb5bae16652e87347f17536b9f1b3eb5daa478ffae98d761abe9f5
license    : MIT
summary    : VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
extract    : no
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - nodejs
    - tree
build    : |
    cd $srcdir
    tar -xf $sources/$version.tar.gz
    cd vscode-$version/
    npm install -g mocha gulp
    ./scripts/npm.sh install
    gulp vscode-linux-x64
install  : |
    cd $srcdir
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/opt/vscode
    cp -R $srcdir/VSCode-linux-x64/* $installdir/opt/vscode/
    ln -s /opt/vscode/code-oss $installdir/usr/bin/Code
    install -Dm644 $srcdir/vscode-$version/resources/linux/code.png /usr/share/pixmaps/code.png
    install -Dm644 $pkgfiles/vscode.desktop /usr/share/applications/vscode.desktop
