name       : vscode
version    : 1.2.0
release    : 5
source     :
    - https://github.com/Microsoft/vscode/archive/1.2.0.tar.gz : c2c08ee85c6d0d02e67a9d1693f004c1c69c0c4e4c02e4c8f9c2ed734f27f748
license    : MIT
component  : editor
summary    : VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
description: |
    VS Code is a new type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - nodejs
build      : |
    npm install -g mocha gulp
    ./scripts/npm.sh install
    gulp vscode-linux-x64
install    : |
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/opt/vscode
    cp -R $workdir/VSCode-linux-x64/* $installdir/opt/vscode/
    ln -s /opt/vscode/code-oss $installdir/usr/bin/code-oss
    install -Dm644 $workdir/vscode-$version/resources/linux/code.png $installdir/usr/share/pixmaps/code-oss.png
    install -Dm644 $pkgfiles/vscode-oss.desktop $installdir/usr/share/applications/vscode-oss.desktop
